language: python
python: 2.7
services:
  - memcached
env:
  - MEMCACHED_URL=mc://localhost:11211 TOX_ENV=py27
  - MEMCACHED_URL=mc://localhost:11211 TOX_ENV=py27-opt
  - MEMCACHED_URL=mc://localhost:11211 TOX_ENV=pyp

notifications:
     email:
         recipients:
             - aidan@shippable.com
             - aidan@shippable.com
         on_success: always
         #on_failure: always
         

install:
  - pip install tox
  
  
script:
  - tox -e $TOX_ENV
